### ISSUE TITLE
Range Rate and Doppler not working?

### ISSUE THREAD

**Issue by Xio1996** [parzivail/SGP.NET#23]
Hi Colby,

Thank you for your great library. 

I might be using the library incorrectly or I might have found a problem in that the Range Rate and hence Doppler shift calculations.

I have attached a test program (Program.txt) and results file (Results.txt) that illustrates what I am seeing. The other information calculated for the satellite is correct when compared to WXtrack. 

As you can see in the program file, I have hacked a workaround that just calculates Range Rate by querying the satellite range 1 second ahead of NOW and then subtracting the ranges. I can then use your code to calculate the doppler shift. The results all seem to match up with WXTrack (Workaround Results.txt).

I hope you can help.

Many thanks

Pete

[Program.txt](https://github.com/parzivail/SGP.NET/files/6906803/Program.txt)
[Results.txt](https://github.com/parzivail/SGP.NET/files/6906818/Results.txt)
[Workaround Results.txt](https://github.com/parzivail/SGP.NET/files/6906825/Workaround.Results.txt)

**Comment by parzivail** [comment]
Hey Pete,

Managed to find the issue, the round-trip conversion between `DateTime` and a `double` amount of total seconds in the propagator back to a `DateTime` turns out to be lossy by about 10 microseconds so the ECI to ECI conversion logic which checks if the ECI coordinate is valid at a given date was failing and resorting to a geodetic fallback without velocity calculation (which is something else that might be broken, but I'll have to check) -- but it's fixed now. I'll update the NuGet with the new package.

Thanks for finding this! Was a sneaky bug to track down. Lemme know if you have any more issues with the new version.

**Comment by Xio1996** [comment]
Hi Colby,

Thank you very much for taking a look so quickly and fixing the bug. I will update the library and continue my satellite adventures! 

Many thanks.

Pete

**Comment by parzivail** [comment]
No problem! The new NuGet package will be here once it's indexed: https://www.nuget.org/packages/SGP.NET/1.2.1

Best of luck! If you need anything else please don't hesitate to open another issue.
